### ISSUE TITLE
Plugin gets disabled automatically on the latest build 1.20.4

### ISSUE THREAD

**Issue by Cerothen** [mfnalex/ChestSort#182]
**Used ChestSort version**
1.20.4 (Purpur server

**Used Spigot version**
This server is running Purpur version git-Purpur-2101 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e1216d on HEAD)

**Describe the bug**
```
at de.jeff_media.chestsort.ChestSortPlugin.onEnable(ChestSortPlugin.java:585) ~[59773-v513673__ChestSortAPI.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2101]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2101]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:655) ~[purpur-1.20.4.jar:git-Purpur-2101]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:566) ~[purpur-1.20.4.jar:git-Purpur-2101]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676) ~[purpur-1.20.4.jar:git-Purpur-2101]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.20.4.jar:git-Purpur-2101]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.4.jar:git-Purpur-2101]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2101]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2101]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**To Reproduce**
Run a server with the latest build git-Purpur-2101

**Expected behavior**
Regular operation

**Additional context**

**Comment by f3ndot** [comment]
Support for 1.20.4 was just released. Use version 13.6.6: https://www.spigotmc.org/resources/chestsort-api.59773/update?update=526373
