### ISSUE TITLE
Could not pass event InventoryCloseEvent to ChestSort v14.0.3

### ISSUE THREAD

**Issue by enigma072485** [mfnalex/ChestSort#192]
**Used ChestSort version**
14.0.3

**Used Spigot version**
Purpur 1.20.6-2214-1bbb033 (MC: 1.20.6)

**Describe the bug**
Started seeing this in the logs....

`ERROR21:35:54
Could not pass event InventoryCloseEvent to ChestSort v14.0.3
Console21:35:54
java.lang.NullPointerException: Cannot invoke "java.lang.Class.descriptorString()" because "parameterType" is null
at io.papermc.paper.pluginremap.reflect.PaperReflection.parameterDescriptor(PaperReflection.java:148) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at io.papermc.paper.pluginremap.reflect.PaperReflection.strippedMethodKey(PaperReflection.java:141) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredMethodName(PaperReflection.java:66) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.1.jar:?]
at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at ChestSort-14.0.3.jar/de.jeff_media.chestsort.handlers.ChestSortOrganizer.getSortableMap(ChestSortOrganizer.java:396) ~[ChestSort-14.0.3.jar:?]
at ChestSort-14.0.3.jar/de.jeff_media.chestsort.handlers.ChestSortOrganizer.sortInventory(ChestSortOrganizer.java:519) ~[ChestSort-14.0.3.jar:?]
at ChestSort-14.0.3.jar/de.jeff_media.chestsort.listeners.ChestSortListener.onPlayerInventoryClose(ChestSortListener.java:305) ~[ChestSort-14.0.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor756.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2214-1bbb033]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1631) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3012) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClose(ServerGamePacketListenerImpl.java:3005) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.network.protocol.game.ServerboundContainerClosePacket.handle(ServerboundContainerClosePacket.java:15) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2214-1bbb033]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**To Reproduce**
Error shows up every time anyone closes an inventory.

**Expected behavior**
No error?

**Additional context**
Fresh update to 1.20.6 from 1.20.4, no issues on previous version.

**Comment by mfnalex** [comment]
Thanks for reporting. That‘s an issue related to Paper‘s jar remapper. I‘ll add a workaround for this (the affected code in ChestSort is pretty bad anyway, so I can clean that up then too).

**Comment by mfnalex** [comment]
Fixed in ChestSort 14.0.4

**Comment by enigma072485** [comment]
Thank you so much for the quick fix! I'll keep an eye on it. 💖
